spring:
  datasource:
    url: jdbc:mysql://localhost:3306/custom_queries
    username: root
    password: Elpipita96!
  jpa:
    database: mysql
    show_sql: true
    hibernate:
      ddl-auto: update
